bazel_dep(name = "abseil-cpp", version = "20240116.2", repo_name = "com_google_absl")

bazel_dep(name = "bazel_skylib", version = "1.8.2")

bazel_dep(name = "googletest", version = "1.14.0.bcr.1", repo_name = "com_google_googletest")

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)

git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    # Use the latest commit from the repo’s main branch; this one is just an example:
    commit = "0e990032f3c5a866e72615cf67e5ce22186dcb97",
)
